bismark_index:
  /home/groups/CEDAR/anno/indices/bismark/bowtie2/hg19/
project_id:
  20191024_BC10
trim_dir:
  samples/trim
map_dir:
  bismarkSE
acc_prom:
  1000
met_prom:
  10000
gtf_file:
  /home/groups/CEDAR/anno/gtf/hg19_ens87.chr.gtf
accBed:
  data/anno/promoters1000.bed
metBed:
  data/anno/promoters10000.bed
bedtools:
  /home/groups/CEDAR/tools/bedtools
cpg:
  /home/groups/CEDAR/woodfin/projects/NMT-seq/20190523_NM/anno/hg19/corr/hg19_CpGislands_UCSC.bed
annoDir:
  data/anno